### PR TITLE
Add structure behaviour

### PR DESCRIPTION
**Pull request by declaneugeneleekennedy**
This enables the use of `mix ecto.dump` and `mix ecto.load` to dump and load database schemas

### CODE REVIEW

**Comment by scouten** [comment]
New function `append_versions` is not covered at all by tests. What does it do?

**Comment by declaneugeneleekennedy** [comment]
@scouten The `append_versions` function adds inserts records into the `schema_migrations` table to that redundant migrations don't get added when using `ecto.load` followed by `ecto.migrate`. That said, it didn't work properly so I've fixed it and have added tests for it too :)

**Comment by ConnorRigby** [comment]
:wave: @declaneugeneleekennedy Would you mind rebasing this pr to `master`. I think it's a good idea to support this, but I don't think using `System.cmd/2` is the correct solution, since `sqlite3` is not actually required to be installed and using `/bin/sh` will not be compatible with Windows systems.

**Comment by ConnorRigby** [comment]
Closing due to inactivity. Feel free to reopen

**Pull request closed without merging**
